### ISSUE TITLE
remove comments

### ISSUE THREAD

**Issue by ploctaux** [digitalsparky/jekyll-minifier#9] opened 2016-07-03 16:01 UTC
is there a way to remove comments in html/css?

**Comment by mohamnag** [comment] 2016-07-07 07:28
this plugin is the best fit I found for minification yet it fails at this single point!

**Comment by digitalsparky** [comment] 2016-07-07 09:02
The only comments that should be remaining are those marked as important in CSS/HTML, such as those identifying conditionals, and legal comments marked as important.

That said, I'll look into the plugin dependencies to see if any of the directives have changed from what they used to be, and correct them.

I can see one comment in one've my own css files that should've been removed but hasn't.

**Comment by digitalsparky** [comment] 2016-07-07 09:03
This is a duplicate of #4, so continuing on there.

**Closed** 2016-07-07 09:03 UTC

**Comment by ploctaux** [comment] 2016-07-07 09:06
Alright, thanks for your help :)

**Comment by digitalsparky** [comment] 2016-07-07 09:55
FYI, new version pushed should resolve these issues.
